insert into missions (
    id, code, title, title_en, title_pl, description,
    time_hint_en, time_hint_pl, category, active, created_at, updated_at
) values
    ('b28b133c-1553-4bc8-97c4-0198d3febc98', 'invite_lunch_sit_together', 'Invite someone to sit with you at lunch', 'Invite someone to sit with you at lunch', 'Zaproś kogoś, żeby usiadł z tobą na lunchu', 'Invite someone to sit with you at lunch.', 'this takes 2 minutes', 'to zajmie 2 minuty', 'social', true, now(), now()),
    ('7c58c539-6f11-416a-9138-5099442b491d', 'learn_classmate_name', 'Learn one classmate''s name you didn''t know', 'Learn one classmate''s name you did not know', 'Naucz się imienia kogoś z klasy, kogo jeszcze nie znałeś/aś', 'Learn one classmate''s name you did not know yet.', 'this takes 2 minutes', 'to zajmie 2 minuty', 'social', true, now(), now()),
    ('fdcda8c8-a8fb-44f3-a91d-d51455ab31fa', 'share_something_funny', 'Share something funny with someone', 'Share something funny with someone', 'Podziel się z kimś czymś zabawnym', 'Share something funny with someone today.', 'this takes 1 minute', 'to zajmie 1 minutę', 'social', true, now(), now()),
    ('ac4e32a9-b92f-477c-ac1a-87415d7f9dca', 'say_thank_you_helper', 'Say thank you to someone who helped you this week', 'Say thank you to someone who helped you this week', 'Podziękuj komuś, kto ci ostatnio pomógł/pomogła', 'Say thank you to someone who helped you this week.', 'this takes 1 minute', 'to zajmie 1 minutę', 'social', true, now(), now()),
    ('12a1d821-76d8-4815-8c11-a025a77220d6', 'try_good_morning_local_language', 'Try saying good morning in the new language', 'Try saying good morning in the new language', 'Spróbuj powiedzieć dzień dobry w nowym języku', 'Try saying good morning in the new language.', 'this takes 1 minute', 'to zajmie 1 minutę', 'new_world', true, now(), now()),
    ('c5d18c96-db94-4222-83de-ce8756362ce2', 'find_nearest_park', 'Find the nearest park or green space near your home', 'Find the nearest park or green space near your home', 'Znajdź najbliższy park lub zielone miejsce blisko domu', 'Find the nearest park or green space near your home.', 'this takes 5 minutes', 'to zajmie 5 minut', 'new_world', true, now(), now()),
    ('70e56044-3ccb-4db8-89f5-d37cb6896bab', 'notice_new_neighborhood_sound', 'Notice one sound your new neighborhood makes that your old one didn''t', 'Notice one sound your new neighborhood makes that your old one did not', 'Zauważ jeden dźwięk w nowej okolicy, którego nie było w starej', 'Notice one sound your new neighborhood makes that your old one did not.', 'this takes 2 minutes', 'to zajmie 2 minuty', 'new_world', true, now(), now()),
    ('c8478a71-4466-4306-8e18-4d44b0390db3', 'find_busiest_market_day', 'Find out what day the local market or store is busiest', 'Find out what day the local market or store is busiest', 'Dowiedz się, w który dzień lokalny sklep lub targ jest najbardziej ruchliwy', 'Find out what day the local market or store is busiest.', 'this takes 3 minutes', 'to zajmie 3 minuty', 'new_world', true, now(), now()),
    ('3535221a-dd1c-41fd-9e1d-1b4df523bca3', 'listen_song_reminds_home', 'Listen to a song that reminds you of home', 'Listen to a song that reminds you of home', 'Posłuchaj piosenki, która przypomina ci dom', 'Listen to a song that reminds you of home.', 'this takes 3 minutes', 'to zajmie 3 minuty', 'old_world', true, now(), now()),
    ('87001a1a-5cb2-4c21-8b1c-f77109f4f324', 'write_favorite_holiday_tradition', 'Write down your favorite holiday tradition from home', 'Write down your favorite holiday tradition from home', 'Zapisz swoją ulubioną tradycję świąteczną z domu', 'Write down your favorite holiday tradition from home.', 'this takes 3 minutes', 'to zajmie 3 minuty', 'old_world', true, now(), now()),
    ('017a2da5-9a2c-4031-b84d-dc8aafa8710d', 'describe_old_bedroom_memory', 'Describe your old bedroom from memory', 'Describe your old bedroom from memory', 'Opisz z pamięci swój stary pokój', 'Describe your old bedroom from memory.', 'this takes 5 minutes', 'to zajmie 5 minut', 'old_world', true, now(), now()),
    ('daf2ee20-b45d-4ae0-bc51-1b47fb0eee91', 'recall_joke_from_home', 'Think of a joke someone back home used to tell you', 'Think of a joke someone back home used to tell you', 'Przypomnij sobie żart, który ktoś z domu ci opowiadał', 'Think of a joke someone back home used to tell you.', 'this takes 2 minutes', 'to zajmie 2 minuty', 'old_world', true, now(), now()),
    ('4a636be8-8e69-4dd9-b52d-cd4454fbdcc3', 'name_one_thing_proud_week', 'Name one thing you''re proud of from this week', 'Name one thing you are proud of from this week', 'Wskaż jedną rzecz, z której jesteś dumny/a w tym tygodniu', 'Name one thing you are proud of from this week.', 'this takes 2 minutes', 'to zajmie 2 minuty', 'reflection', true, now(), now()),
    ('782b5e6b-4e6e-43c5-8aa1-843ddfb69d66', 'write_something_surprised_today', 'Write down one thing that surprised you today', 'Write down one thing that surprised you today', 'Zapisz jedną rzecz, która cię dziś zaskoczyła', 'Write down one thing that surprised you today.', 'this takes 1 minute', 'to zajmie 1 minutę', 'reflection', true, now(), now()),
    ('a2278653-fbb4-424d-9213-dc9fa2009750', 'one_word_today_felt', 'Think of one word that describes how today felt', 'Think of one word that describes how today felt', 'Wymyśl jedno słowo, które opisuje dzisiejszy dzień', 'Think of one word that describes how today felt.', 'this takes 1 minute', 'to zajmie 1 minutę', 'reflection', true, now(), now()),
    ('98004773-9587-437f-9bb1-bf3707e9c60d', 'notice_small_win_today', 'Notice one small thing that went better than you expected', 'Notice one small thing that went better than you expected', 'Zauważ jedną małą rzecz, która poszła lepiej, niż się spodziewałeś/aś', 'Notice one small thing that went better than you expected.', 'this takes 2 minutes', 'to zajmie 2 minuty', 'reflection', true, now(), now()),
    ('d969912d-8d93-4170-83d2-01467d2b0346', 'find_nearest_library', 'Find out where the library is near your home', 'Find out where the library is near your home', 'Dowiedz się, gdzie jest biblioteka blisko domu', 'Find out where the library is near your home.', 'this takes 3 minutes', 'to zajmie 3 minuty', 'exploration', true, now(), now()),
    ('08536acb-39d6-4ebb-adf5-2b72c82a3948', 'look_up_local_holiday', 'Look up one holiday celebrated here that''s new to you', 'Look up one holiday celebrated here that is new to you', 'Sprawdź jedno święto obchodzone tutaj, którego wcześniej nie znałeś/aś', 'Look up one holiday celebrated here that is new to you.', 'this takes 3 minutes', 'to zajmie 3 minuty', 'exploration', true, now(), now()),
    ('251e5cb7-47c7-498f-af31-a7ee18249de4', 'find_new_walk_route', 'Find one new route to walk or bike this week', 'Find one new route to walk or bike this week', 'Znajdź nową trasę na spacer lub rower w tym tygodniu', 'Find one new route to walk or bike this week.', 'this takes 5 minutes', 'to zajmie 5 minut', 'exploration', true, now(), now()),
    ('b8e30c68-a3ef-434a-a09d-65a555f0b2e7', 'discover_recess_game', 'Discover what game kids play at recess here', 'Discover what game kids play at recess here', 'Dowiedz się, w co bawią się dzieci na przerwie', 'Discover what game kids play at recess here.', 'this takes 3 minutes', 'to zajmie 3 minuty', 'exploration', true, now(), now())
on conflict (code) do nothing;
